version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/usr/src/app/bot"
    volumes:
      - .:/usr/src/app/bot
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"

  ##  To enable redis cache uncomment the following lines
  # redis_cache:
  #  image: redis:6.2-alpine
  #  restart: always
  #  command: redis-server --port $REDIS_PORT --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
  #  env_file:
  #    - ".env"
  #  volumes:
  #    - cache:/data

  # reverse-proxy:
  #  container_name: nginx-reverse-proxy
  #  stop_signal: SIGINT
  #  restart: always
  #  image: nginx:latest
  #  ports:
  #    - '80:80'
  #  volumes:
  #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf


## Uncomment the following lines if you want to use a volume for the database
# volumes:
#  cache: { }
